### PR TITLE
Feature - Revise templates' structure

### PR DESCRIPTION
**Pull request by trgiangdo**

### CODE REVIEW

**Review by jrobinAV — APPROVED** [review]
So we keep the header on the post gen script but not on the files that will be modified by the user. Makes sense.

LGTM

**Comment by trgiangdo** [comment]
There is an linting error. I added a commit to fix it, which worked on my machine, but somehow did not work on Github action.

My guess is that it's due to the OS (mine is MacOS, and the linting job is running in Ubuntu). If it's ok, I will try to fix it latter.

**Comment by trgiangdo** [comment]
@FlorianJacta did clarify that the root.md is not the homepage, but it is was is shared by every page like the navbar and the general logic of the application.

We need to update the explanation in `multi-page-gui/{{cookiecutter.application_name}}/pages/root.py` and `multi-page-gui/{{cookiecutter.application_name}}`.

**Review by FabienLelaquais — APPROVED** [review]
So that is FAR better, in my opinion.

I have a last comment to make though.
The name of the generated page variables is misleading.

`root_md`, `page1_md` and so fourth are NOT Markdown. That is, not anymore after the Markdown constructor was invoked. They are Pages.
You don't care about whether they are Markdown or HTML or more in the future in the main module, when you actually use those pages.


I would really prefer having
root_md -> root_page
page1_md -> page1
and so on

**Review by jrobinAV — APPROVED** [review]

**Pull request merged**
